### ISSUE TITLE
Invoke-RestMethod is giving "Request_ResourceNotFound" error but Resource is available on azure

### ISSUE THREAD

**Issue by shwetajan20** [EirikHaughom/ADME#5]
Hi @EirikHaughom ,

I was trying to implement this Logic app for one of our client but getting below error while trying to invoke-rest method

Invoke-RestMethod `
    -Uri "https://graph.microsoft.com/v1.0/servicePrincipals/$GraphOID/appRoleAssignments" `
    -ContentType "application/json" `
    -Method POST `
    -Headers $headers `
    -Body $groupBody

I can see the Microsoft graph application got created in the enterprise application section but still i am getting below error- 

Invoke-RestMethod: {"error":{"code":"Request_ResourceNotFound","message":"Resource '0000000-000000-429c-a03c-ff59b2692a7e' does not exist or one of its queried reference-property objects are not present.","innerError":{"date":"2023-05-09T11:17:00","request-id":"1e404957-624a-000-8ebb-a06b9da86001","client-request-id":"00000-624a-400-8ebb-a06b9da86001"}}}

![image](https://github.com/EirikHaughom/ADME/assets/40286296/5af87213-e4d3-4505-8c8e-fca34da1e2c5)

**Comment by EirikHaughom** [comment]
Can you output the $groupBody content and validate which entry that object ID relates to?

Object ID: 0000000-000000-429c-a03c-ff59b2692a7e

**Comment by shwetajan20** [comment]
I checked it and verified object ID relates to Microsoft graph.

**Comment by shwetajan20** [comment]
Here is the output for $groupBody

![image](https://github.com/EirikHaughom/ADME/assets/40286296/0fc3ad3e-3d40-42dd-b5f3-9fa656be0f51)

**Comment by EirikHaughom** [comment]
Can you verify that the principalId = the objectId of the Logic App Managed Identity and that appRoleId is the correct ID for the graph role Group.Read.All ?

You can also use graph explorer to achieve the same: https://developer.microsoft.com/en-us/graph/graph-explorer?request=servicePrincipals%2F%7Bid%7D%2FappRoleAssignments&method=POST&version=v1.0&GraphUrl=https://graph.microsoft.com&requestBody=eyJwcmluY2lwYWxJZCI6InByaW5jaXBhbElkLXZhbHVlIiwicmVzb3VyY2VJZCI6InJlc291cmNlSWQtdmFsdWUiLCJhcHBSb2xlSWQiOiJhcHBSb2xlSWQtdmFsdWUifQ==&headers=W3sibmFtZSI6IkNvbnRlbnQtdHlwZSIsInZhbHVlIjoiYXBwbGljYXRpb24vanNvbiJ9XQ==

**Comment by shwetajan20** [comment]
principalId = the objectId of the Logic App Managed Identity - yes it is

Not sure how to confirm this  - appRoleId is the correct ID for the graph role Group.Read.All ?

also running the graph explorer got the same error

![image](https://github.com/EirikHaughom/ADME/assets/40286296/ddd02f8b-5185-47ff-8572-a0ad1b9de497)

**Comment by EirikHaughom** [comment]
This should list all the approles on your Graph:
`(az ad sp show --id 00000003-0000-0000-c000-000000000000 | convertfrom-json).approles | select value,id | where {$_.value -eq "Group.Read.All"}`

**Comment by shwetajan20** [comment]
![image](https://github.com/EirikHaughom/ADME/assets/40286296/dda4df3a-1692-43a0-8ad8-e577454412d3)

yes it is also correct

**Comment by EirikHaughom** [comment]
> I checked it and verified object ID relates to Microsoft graph.

So here you say that the ID (0000000-000000-429c-a03c-ff59b2692a7e) relates to Graph, but the ResourceId seems to be something different?
<img width="475" alt="image" src="https://github.com/EirikHaughom/ADME/assets/26802184/21cc2ed8-6021-4dd1-928a-b8230b6d582a">

It's a bit hard to diagnose without seeing the IDs etc.

As an alternative you can grant the permissions using Azure AD, but think they have to be scopet at the tenant level and not the individual AAD group: https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps#assign-app-roles-to-applications

**Comment by shwetajan20** [comment]
One thing..... i am not able to see resource id in App registration section but in Enterprise application section in AAD.

**Comment by shwetajan20** [comment]
So here you say that the ID (0000000-000000-429c-a03c-ff59b2692a7e) relates to Graph, but the ResourceId seems to be something different?

**no both are same**

**Comment by EirikHaughom** [comment]
Updated the documentation to resolve this issue. Thank you for the collaboration!
